-- auto-generated by the Snowsight data loading wizard
-- (top level "store" JSON object will be stripped)

CREATE TABLE "TEST"."PUBLIC"."store2" ( v VARIANT ); 

CREATE TEMP FILE FORMAT "TEST"."PUBLIC"."temp_file_format_infer_2024-07-18T10:54:18.360Z"
	TYPE=JSON
    STRIP_OUTER_ARRAY=FALSE
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "TEST"."PUBLIC"."store2" 
FROM (SELECT $1:store::VARCHAR
	FROM '@"TEST"."PUBLIC"."__snowflake_temp_import_files__"') 
FILES = ('2024-07-18T10:53:38.465Z/store.json') 
FILE_FORMAT = '"TEST"."PUBLIC"."temp_file_format_infer_2024-07-18T10:54:18.360Z"' 
ON_ERROR=ABORT_STATEMENT 
-- For more details, see: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table
